### ISSUE TITLE
Feature/Création de la page de bienvenue

### ISSUE THREAD

**Issue by SkyNightdev** [mdeport/budget_app#13]
Création de la page de bienvenue : 

Les Gandes parties : 

1. Gérez facilement vos dépenses !

BudgetApp est une solution pour que vous puissiez gérez et adopter des stratégies afin de vous aider à économiser de l’argent et en gagner.

2. Gagnez du temps !

Remplacez 80% du temps à parler avec des conseillers par cette applications, les conseils et les aides sont automatisés en fonction de chaque utilisateur.

3. Maitrisez toutes vos dépenses !

Vous pourrez gérez absolument toutes les catégories de dépenses et de gains dans cette application en personnalisant vous-même les catégories en question.

4. Analyse et Compétence !
Vous avez un accès sur des analyses de graphiques et d’historique pour vous aidera à mieux visualiser vos dépenses et gains.

5. Personnalisation !
Vous avez la possibilité de personnalisez en plus de votre contenu, l’apparence de l’application à votre guise !

**Comment by mdeport** [comment]
la pr a bien été livré
